package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad")
public class Actividad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idActividad;
	private String descripcion;
	private Integer importe;
	private Boolean valides;
	private Set<EmpleadoActividad> empleadoactividads = new HashSet<EmpleadoActividad>(0);

	public Actividad() {
	}

	public Actividad(String descripcion, Integer importe, Boolean valides) {
		this.descripcion = descripcion;
		this.importe = importe;
		this.valides = valides;
	}

	public Actividad(String descripcion, Integer importe, Boolean valides,
			Set<EmpleadoActividad> empleadoactividads) {
		this.descripcion = descripcion;
		this.importe = importe;
		this.valides = valides;
		this.empleadoactividads = empleadoactividads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idActividad", unique = true, nullable = false)
	public Integer getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(Integer idActividad) {
		this.idActividad = idActividad;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "importe", nullable = false)
	public Integer getImporte() {
		return this.importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	@Column(name = "valides", nullable = false)
	public Boolean getValides() {
		return this.valides;
	}

	public void setValides(Boolean valides) {
		this.valides = valides;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividad")
	public Set<EmpleadoActividad> getEmpleadoactividads() {
		return this.empleadoactividads;
	}

	public void setEmpleadoactividads(Set<EmpleadoActividad> empleadoactividads) {
		this.empleadoactividads = empleadoactividads;
	}

}
