package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compraproducto generated by hbm2java
 */
@Entity
@Table(name = "compraproducto")
public class CompraProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCompraProducto;
	private Producto producto;
	private Semana semana;
	private Double peso;
	private Double cantidad;
	private Double importeTotal;
	private Double importeUnitario;

	public CompraProducto() {
	}

	public CompraProducto(Producto producto, Semana semana, Double importeTotal) {
		this.producto = producto;
		this.semana = semana;
		this.importeTotal = importeTotal;
	}

	public CompraProducto(Producto producto, Semana semana, Double peso,
			Double cantidad, Double importeTotal, Double importeUnitario) {
		this.producto = producto;
		this.semana = semana;
		this.peso = peso;
		this.cantidad = cantidad;
		this.importeTotal = importeTotal;
		this.importeUnitario = importeUnitario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCompraProducto", unique = true, nullable = false)
	public Integer getIdCompraProducto() {
		return this.idCompraProducto;
	}

	public void setIdCompraProducto(Integer idCompraProducto) {
		this.idCompraProducto = idCompraProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semana", nullable = false)
	public Semana getSemana() {
		return this.semana;
	}

	public void setSemana(Semana semana) {
		this.semana = semana;
	}

	@Column(name = "peso", precision = 22, scale = 0)
	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	@Column(name = "cantidad", precision = 22, scale = 0)
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "importeTotal", nullable = false, precision = 22, scale = 0)
	public Double getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(Double importeTotal) {
		this.importeTotal = importeTotal;
	}

	@Column(name = "importeUnitario", precision = 22, scale = 0)
	public Double getImporteUnitario() {
		return this.importeUnitario;
	}

	public void setImporteUnitario(Double importeUnitario) {
		this.importeUnitario = importeUnitario;
	}

}
