package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Consolidadoventaremolque generated by hbm2java
 */
@Entity
@Table(name = "consolidadoventaremolque")
public class ConsolidadoVentaRemolque implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idConsolidadoVentaRemolque;
	private VentaRemolque ventaremolque;
	private Comida comida;
	private Double pollosVendidos;
	private Double papasVendidas;
	private Double totalVenta;
	private Double billetes;
	private Double monedas;
	private Double diferencia;

	public ConsolidadoVentaRemolque() {
	}

	public ConsolidadoVentaRemolque(VentaRemolque ventaremolque, Comida comida,
			Double pollosVendidos, Double papasVendidas, Double totalVenta,
			Double billetes, Double monedas, Double diferencia) {
		this.ventaremolque = ventaremolque;
		this.comida = comida;
		this.pollosVendidos = pollosVendidos;
		this.papasVendidas = papasVendidas;
		this.totalVenta = totalVenta;
		this.billetes = billetes;
		this.monedas = monedas;
		this.diferencia = diferencia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idConsolidadoVentaRemolque", unique = true, nullable = false)
	public Integer getIdConsolidadoVentaRemolque() {
		return this.idConsolidadoVentaRemolque;
	}

	public void setIdConsolidadoVentaRemolque(Integer idConsolidadoVentaRemolque) {
		this.idConsolidadoVentaRemolque = idConsolidadoVentaRemolque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ventaRemolque", nullable = false)
	public VentaRemolque getVentaremolque() {
		return this.ventaremolque;
	}

	public void setVentaremolque(VentaRemolque ventaremolque) {
		this.ventaremolque = ventaremolque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comida", nullable = false)
	public Comida getComida() {
		return this.comida;
	}

	public void setComida(Comida comida) {
		this.comida = comida;
	}

	@Column(name = "pollosVendidos", nullable = false, precision = 22, scale = 0)
	public Double getPollosVendidos() {
		return this.pollosVendidos;
	}

	public void setPollosVendidos(Double pollosVendidos) {
		this.pollosVendidos = pollosVendidos;
	}

	@Column(name = "papasVendidas", nullable = false, precision = 22, scale = 0)
	public Double getPapasVendidas() {
		return this.papasVendidas;
	}

	public void setPapasVendidas(Double papasVendidas) {
		this.papasVendidas = papasVendidas;
	}

	@Column(name = "totalVenta", nullable = false, precision = 22, scale = 0)
	public Double getTotalVenta() {
		return this.totalVenta;
	}

	public void setTotalVenta(Double totalVenta) {
		this.totalVenta = totalVenta;
	}

	@Column(name = "billetes", nullable = false, precision = 22, scale = 0)
	public Double getBilletes() {
		return this.billetes;
	}

	public void setBilletes(Double billetes) {
		this.billetes = billetes;
	}

	@Column(name = "monedas", nullable = false, precision = 22, scale = 0)
	public Double getMonedas() {
		return this.monedas;
	}

	public void setMonedas(Double monedas) {
		this.monedas = monedas;
	}

	@Column(name = "diferencia", nullable = false, precision = 22, scale = 0)
	public Double getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(Double diferencia) {
		this.diferencia = diferencia;
	}

}
