package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dia generated by hbm2java
 */
@Entity
@Table(name = "dia")
public class Dia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDia;
	private String descripcion;
	private Set<SemanaDia> semanadias = new HashSet<SemanaDia>(0);

	public Dia() {
	}

	public Dia(String descripcion) {
		this.descripcion = descripcion;
	}

	public Dia(String descripcion, Set<SemanaDia> semanadias) {
		this.descripcion = descripcion;
		this.semanadias = semanadias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDia", unique = true, nullable = false)
	public Integer getIdDia() {
		return this.idDia;
	}

	public void setIdDia(Integer idDia) {
		this.idDia = idDia;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dia")
	public Set<SemanaDia> getSemanadias() {
		return this.semanadias;
	}

	public void setSemanadias(Set<SemanaDia> semanadias) {
		this.semanadias = semanadias;
	}

}
