package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empleadoactividad generated by hbm2java
 */
@Entity
@Table(name = "empleadoactividad")
public class EmpleadoActividad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEmpleadoActividad;
	private Empleado empleado;
	private Actividad actividad;
	private Semana semana;

	public EmpleadoActividad() {
	}

	public EmpleadoActividad(Empleado empleado, Actividad actividad,
			Semana semana) {
		this.empleado = empleado;
		this.actividad = actividad;
		this.semana = semana;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEmpleadoActividad", unique = true, nullable = false)
	public Integer getIdEmpleadoActividad() {
		return this.idEmpleadoActividad;
	}

	public void setIdEmpleadoActividad(Integer idEmpleadoActividad) {
		this.idEmpleadoActividad = idEmpleadoActividad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "empleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "semana", nullable = false)
	public Semana getSemana() {
		return this.semana;
	}

	public void setSemana(Semana semana) {
		this.semana = semana;
	}

}
