package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEmpleado;
	private String telefono;
	private String nombre;
	private Set<VentaRemolque> ventaremolquesForChava = new HashSet<VentaRemolque>(0);
	private Set<EmpleadoActividad> empleadoactividads = new HashSet<EmpleadoActividad>(0);
	private Set<VentaRemolque> ventaremolquesForParillero = new HashSet<VentaRemolque>(0);

	public Empleado() {
	}

	public Empleado(String nombre) {
		this.nombre = nombre;
	}

	public Empleado(String telefono, String nombre,
			Set<VentaRemolque> ventaremolquesForChava,
			Set<EmpleadoActividad> empleadoactividads,
			Set<VentaRemolque> ventaremolquesForParillero) {
		this.telefono = telefono;
		this.nombre = nombre;
		this.ventaremolquesForChava = ventaremolquesForChava;
		this.empleadoactividads = empleadoactividads;
		this.ventaremolquesForParillero = ventaremolquesForParillero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEmpleado", unique = true, nullable = false)
	public Integer getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Integer idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoByChava")
	public Set<VentaRemolque> getVentaremolquesForChava() {
		return this.ventaremolquesForChava;
	}

	public void setVentaremolquesForChava(
			Set<VentaRemolque> ventaremolquesForChava) {
		this.ventaremolquesForChava = ventaremolquesForChava;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<EmpleadoActividad> getEmpleadoactividads() {
		return this.empleadoactividads;
	}

	public void setEmpleadoactividads(Set<EmpleadoActividad> empleadoactividads) {
		this.empleadoactividads = empleadoactividads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoByParillero")
	public Set<VentaRemolque> getVentaremolquesForParillero() {
		return this.ventaremolquesForParillero;
	}

	public void setVentaremolquesForParillero(
			Set<VentaRemolque> ventaremolquesForParillero) {
		this.ventaremolquesForParillero = ventaremolquesForParillero;
	}

}
