package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ganancia generated by hbm2java
 */
@Entity
@Table(name = "ganancia")
public class Ganancia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idGanancia;
	private Semana semana;
	private Double pagoJorge;
	private Double gasolinaJorge;
	private Double importeTotal;
	private Double importeLibre;

	public Ganancia() {
	}

	public Ganancia(Semana semana, Double pagoJorge, Double gasolinaJorge,
			Double importeTotal, Double importeLibre) {
		this.semana = semana;
		this.pagoJorge = pagoJorge;
		this.gasolinaJorge = gasolinaJorge;
		this.importeTotal = importeTotal;
		this.importeLibre = importeLibre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGanancia", unique = true, nullable = false)
	public Integer getIdGanancia() {
		return this.idGanancia;
	}

	public void setIdGanancia(Integer idGanancia) {
		this.idGanancia = idGanancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semana", nullable = false)
	public Semana getSemana() {
		return this.semana;
	}

	public void setSemana(Semana semana) {
		this.semana = semana;
	}

	@Column(name = "pagoJorge", nullable = false, precision = 22, scale = 0)
	public Double getPagoJorge() {
		return this.pagoJorge;
	}

	public void setPagoJorge(Double pagoJorge) {
		this.pagoJorge = pagoJorge;
	}

	@Column(name = "gasolinaJorge", nullable = false, precision = 22, scale = 0)
	public Double getGasolinaJorge() {
		return this.gasolinaJorge;
	}

	public void setGasolinaJorge(Double gasolinaJorge) {
		this.gasolinaJorge = gasolinaJorge;
	}

	@Column(name = "importeTotal", nullable = false, precision = 22, scale = 0)
	public Double getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(Double importeTotal) {
		this.importeTotal = importeTotal;
	}

	@Column(name = "importeLibre", nullable = false, precision = 22, scale = 0)
	public Double getImporteLibre() {
		return this.importeLibre;
	}

	public void setImporteLibre(Double importeLibre) {
		this.importeLibre = importeLibre;
	}

}
