package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gasto generated by hbm2java
 */
@Entity
@Table(name = "gasto")
public class Gasto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idGasto;
	private String descripcion;
	private Set<GastoSemana> gastosemanas = new HashSet<GastoSemana>(0);

	public Gasto() {
	}

	public Gasto(String descripcion) {
		this.descripcion = descripcion;
	}

	public Gasto(String descripcion, Set<GastoSemana> gastosemanas) {
		this.descripcion = descripcion;
		this.gastosemanas = gastosemanas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGasto", unique = true, nullable = false)
	public Integer getIdGasto() {
		return this.idGasto;
	}

	public void setIdGasto(Integer idGasto) {
		this.idGasto = idGasto;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gasto")
	public Set<GastoSemana> getGastosemanas() {
		return this.gastosemanas;
	}

	public void setGastosemanas(Set<GastoSemana> gastosemanas) {
		this.gastosemanas = gastosemanas;
	}

}
