package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Movimientopapas generated by hbm2java
 */
@Entity
@Table(name = "movimientopapas")
public class MovimientoPapas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idMovimientoPapas;
	private VentaRemolque ventaremolqueByRemolqueOrigen;
	private SemanaDia semanadia;
	private VentaRemolque ventaremolqueByRemolqueDestino;
	private Double cantidad;

	public MovimientoPapas() {
	}

	public MovimientoPapas(VentaRemolque ventaremolqueByRemolqueOrigen,
			SemanaDia semanadia, VentaRemolque ventaremolqueByRemolqueDestino,
			Double cantidad) {
		this.ventaremolqueByRemolqueOrigen = ventaremolqueByRemolqueOrigen;
		this.semanadia = semanadia;
		this.ventaremolqueByRemolqueDestino = ventaremolqueByRemolqueDestino;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMovimientoPapas", unique = true, nullable = false)
	public Integer getIdMovimientoPapas() {
		return this.idMovimientoPapas;
	}

	public void setIdMovimientoPapas(Integer idMovimientoPapas) {
		this.idMovimientoPapas = idMovimientoPapas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "remolqueOrigen", nullable = false)
	public VentaRemolque getVentaremolqueByRemolqueOrigen() {
		return this.ventaremolqueByRemolqueOrigen;
	}

	public void setVentaremolqueByRemolqueOrigen(
			VentaRemolque ventaremolqueByRemolqueOrigen) {
		this.ventaremolqueByRemolqueOrigen = ventaremolqueByRemolqueOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semanaDia", nullable = false)
	public SemanaDia getSemanadia() {
		return this.semanadia;
	}

	public void setSemanadia(SemanaDia semanadia) {
		this.semanadia = semanadia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "remolqueDestino", nullable = false)
	public VentaRemolque getVentaremolqueByRemolqueDestino() {
		return this.ventaremolqueByRemolqueDestino;
	}

	public void setVentaremolqueByRemolqueDestino(
			VentaRemolque ventaremolqueByRemolqueDestino) {
		this.ventaremolqueByRemolqueDestino = ventaremolqueByRemolqueDestino;
	}

	@Column(name = "cantidad", nullable = false)
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
