package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProducto;
	private String descripcion;
	private Set<CompraProducto> compraproductos = new HashSet<CompraProducto>(0);

	public Producto() {
	}

	public Producto(String descripcion) {
		this.descripcion = descripcion;
	}

	public Producto(String descripcion, Set<CompraProducto> compraproductos) {
		this.descripcion = descripcion;
		this.compraproductos = compraproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProducto", unique = true, nullable = false)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<CompraProducto> getCompraproductos() {
		return this.compraproductos;
	}

	public void setCompraproductos(Set<CompraProducto> compraproductos) {
		this.compraproductos = compraproductos;
	}

}
