package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Remolque generated by hbm2java
 */
@Entity
@Table(name = "remolque")
public class Remolque implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRemolque;
	private String descripcion;
	private Set<VentaRemolque> ventaremolques = new HashSet<VentaRemolque>(0);

	public Remolque() {
	}

	public Remolque(String descripcion, Set<VentaRemolque> ventaremolques) {
		this.descripcion = descripcion;
		this.ventaremolques = ventaremolques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRemolque", unique = true, nullable = false)
	public Integer getIdRemolque() {
		return this.idRemolque;
	}

	public void setIdRemolque(Integer idRemolque) {
		this.idRemolque = idRemolque;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "remolque")
	public Set<VentaRemolque> getVentaremolques() {
		return this.ventaremolques;
	}

	public void setVentaremolques(Set<VentaRemolque> ventaremolques) {
		this.ventaremolques = ventaremolques;
	}

}
