package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semana generated by hbm2java
 */
@Entity
@Table(name = "semana")
public class Semana implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSemana;
	private Date fechaInicio;
	private Date fechaFin;
	private Set<SemanaDia> semanadias = new HashSet<SemanaDia>(0);
	private Set<EmpleadoActividad> empleadoactividads = new HashSet<EmpleadoActividad>(0);
	private Set<Ganancia> ganancias = new HashSet<Ganancia>(0);
	private Set<CompraProducto> compraproductos = new HashSet<CompraProducto>(0);

	public Semana() {
	}

	public Semana(Date fechaInicio, Date fechaFin) {
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Semana(Date fechaInicio, Date fechaFin, Set<SemanaDia> semanadias,
			Set<EmpleadoActividad> empleadoactividads, Set<Ganancia> ganancias,
			Set<CompraProducto> compraproductos) {
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.semanadias = semanadias;
		this.empleadoactividads = empleadoactividads;
		this.ganancias = ganancias;
		this.compraproductos = compraproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSemana", unique = true, nullable = false)
	public Integer getIdSemana() {
		return this.idSemana;
	}

	public void setIdSemana(Integer idSemana) {
		this.idSemana = idSemana;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicio", nullable = false, length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFin", nullable = false, length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semana")
	public Set<SemanaDia> getSemanadias() {
		return this.semanadias;
	}

	public void setSemanadias(Set<SemanaDia> semanadias) {
		this.semanadias = semanadias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semana")
	public Set<EmpleadoActividad> getEmpleadoactividads() {
		return this.empleadoactividads;
	}

	public void setEmpleadoactividads(Set<EmpleadoActividad> empleadoactividads) {
		this.empleadoactividads = empleadoactividads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semana")
	public Set<Ganancia> getGanancias() {
		return this.ganancias;
	}

	public void setGanancias(Set<Ganancia> ganancias) {
		this.ganancias = ganancias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semana")
	public Set<CompraProducto> getCompraproductos() {
		return this.compraproductos;
	}

	public void setCompraproductos(Set<CompraProducto> compraproductos) {
		this.compraproductos = compraproductos;
	}

}
