package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semanadia generated by hbm2java
 */
@Entity
@Table(name = "semanadia")
public class SemanaDia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSemanaDia;
	private Dia dia;
	private Semana semana;
	private Set<ServicioCompra> serviciocompras = new HashSet<ServicioCompra>(0);
	private Set<MovimientoPapas> movimientopapases = new HashSet<MovimientoPapas>(0);
	private Set<VentaRemolque> ventaremolques = new HashSet<VentaRemolque>(0);
	private Set<VentaRemolquePieza> ventaremolquepiezas = new HashSet<VentaRemolquePieza>(0);
	private Set<MovimientoPollos> movimientopolloses = new HashSet<MovimientoPollos>(0);
	private Set<GastoSemana> gastosemanas = new HashSet<GastoSemana>(0);

	public SemanaDia() {
	}

	public SemanaDia(Dia dia, Semana semana) {
		this.dia = dia;
		this.semana = semana;
	}

	public SemanaDia(Dia dia, Semana semana,
			Set<ServicioCompra> serviciocompras,
			Set<MovimientoPapas> movimientopapases,
			Set<VentaRemolque> ventaremolques,
			Set<VentaRemolquePieza> ventaremolquepiezas,
			Set<MovimientoPollos> movimientopolloses,
			Set<GastoSemana> gastosemanas) {
		this.dia = dia;
		this.semana = semana;
		this.serviciocompras = serviciocompras;
		this.movimientopapases = movimientopapases;
		this.ventaremolques = ventaremolques;
		this.ventaremolquepiezas = ventaremolquepiezas;
		this.movimientopolloses = movimientopolloses;
		this.gastosemanas = gastosemanas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSemanaDia", unique = true, nullable = false)
	public Integer getIdSemanaDia() {
		return this.idSemanaDia;
	}

	public void setIdSemanaDia(Integer idSemanaDia) {
		this.idSemanaDia = idSemanaDia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dia", nullable = false)
	public Dia getDia() {
		return this.dia;
	}

	public void setDia(Dia dia) {
		this.dia = dia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semana", nullable = false)
	public Semana getSemana() {
		return this.semana;
	}

	public void setSemana(Semana semana) {
		this.semana = semana;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<ServicioCompra> getServiciocompras() {
		return this.serviciocompras;
	}

	public void setServiciocompras(Set<ServicioCompra> serviciocompras) {
		this.serviciocompras = serviciocompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<MovimientoPapas> getMovimientopapases() {
		return this.movimientopapases;
	}

	public void setMovimientopapases(Set<MovimientoPapas> movimientopapases) {
		this.movimientopapases = movimientopapases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<VentaRemolque> getVentaremolques() {
		return this.ventaremolques;
	}

	public void setVentaremolques(Set<VentaRemolque> ventaremolques) {
		this.ventaremolques = ventaremolques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<VentaRemolquePieza> getVentaremolquepiezas() {
		return this.ventaremolquepiezas;
	}

	public void setVentaremolquepiezas(
			Set<VentaRemolquePieza> ventaremolquepiezas) {
		this.ventaremolquepiezas = ventaremolquepiezas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<MovimientoPollos> getMovimientopolloses() {
		return this.movimientopolloses;
	}

	public void setMovimientopolloses(Set<MovimientoPollos> movimientopolloses) {
		this.movimientopolloses = movimientopolloses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semanadia")
	public Set<GastoSemana> getGastosemanas() {
		return this.gastosemanas;
	}

	public void setGastosemanas(Set<GastoSemana> gastosemanas) {
		this.gastosemanas = gastosemanas;
	}

}
