package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio")
public class Servicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idServicio;
	private String descripcion;
	private Set<ServicioCompra> serviciocompras = new HashSet<ServicioCompra>(0);

	public Servicio() {
	}

	public Servicio(String descripcion) {
		this.descripcion = descripcion;
	}

	public Servicio(String descripcion, Set<ServicioCompra> serviciocompras) {
		this.descripcion = descripcion;
		this.serviciocompras = serviciocompras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idServicio", unique = true, nullable = false)
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<ServicioCompra> getServiciocompras() {
		return this.serviciocompras;
	}

	public void setServiciocompras(Set<ServicioCompra> serviciocompras) {
		this.serviciocompras = serviciocompras;
	}

}
