package com.mx.pollos.model;

// Generated 08-dic-2015 22:32:59 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ventaremolquepieza generated by hbm2java
 */
@Entity
@Table(name = "ventaremolquepieza")
public class VentaRemolquePieza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idVentaRemolquePieza;
	private VentaRemolque ventaremolque;
	private Pieza pieza;
	private SemanaDia semanadia;
	private Double cantidad;

	public VentaRemolquePieza() {
	}

	public VentaRemolquePieza(VentaRemolque ventaremolque, Pieza pieza,
			SemanaDia semanadia, Double cantidad) {
		this.ventaremolque = ventaremolque;
		this.pieza = pieza;
		this.semanadia = semanadia;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVentaRemolquePieza", unique = true, nullable = false)
	public Integer getIdVentaRemolquePieza() {
		return this.idVentaRemolquePieza;
	}

	public void setIdVentaRemolquePieza(Integer idVentaRemolquePieza) {
		this.idVentaRemolquePieza = idVentaRemolquePieza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ventaRemolque", nullable = false)
	public VentaRemolque getVentaremolque() {
		return this.ventaremolque;
	}

	public void setVentaremolque(VentaRemolque ventaremolque) {
		this.ventaremolque = ventaremolque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pieza", nullable = false)
	public Pieza getPieza() {
		return this.pieza;
	}

	public void setPieza(Pieza pieza) {
		this.pieza = pieza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semanaDia", nullable = false)
	public SemanaDia getSemanadia() {
		return this.semanadia;
	}

	public void setSemanadia(SemanaDia semanadia) {
		this.semanadia = semanadia;
	}

	@Column(name = "cantidad", nullable = false, precision = 22, scale = 0)
	public Double getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
